# This file was automatically generated by SWIG
package LWES;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package LWESc;
bootstrap LWES;
package LWES;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package LWES;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package LWES;

*create_db = *LWESc::create_db;
*destroy_db = *LWESc::destroy_db;
*create_emitter = *LWESc::create_emitter;
*create_emitter_with_ttl = *LWESc::create_emitter_with_ttl;
*emit = *LWESc::emit;
*emitto = *LWESc::emitto;
*destroy_emitter = *LWESc::destroy_emitter;
*create_event = *LWESc::create_event;
*create_event_with_encoding = *LWESc::create_event_with_encoding;
*set_uint16 = *LWESc::set_uint16;
*get_uint16 = *LWESc::get_uint16;
*set_int16 = *LWESc::set_int16;
*get_int16 = *LWESc::get_int16;
*set_uint32 = *LWESc::set_uint32;
*get_uint32 = *LWESc::get_uint32;
*set_int32 = *LWESc::set_int32;
*get_int32 = *LWESc::get_int32;
*set_uint64 = *LWESc::set_uint64;
*get_uint64 = *LWESc::get_uint64;
*set_int64 = *LWESc::set_int64;
*get_int64 = *LWESc::get_int64;
*set_string = *LWESc::set_string;
*get_string = *LWESc::get_string;
*set_ip_addr = *LWESc::set_ip_addr;
*get_ip_addr = *LWESc::get_ip_addr;
*set_boolean = *LWESc::set_boolean;
*get_boolean = *LWESc::get_boolean;
*destroy_event = *LWESc::destroy_event;
*current_time_millis = *LWESc::current_time_millis;

# ------- VARIABLE STUBS --------

package LWES;

1;
